config/routes.rb
Rails.application.routes.draw do
  resources :plays
  resources :games
  resources :comments
  resources :users
  resources :posts_tags
  resources :tags
  resources :posts

  root 'posts#recent'

end

app/models/posts_tag.rb
class PostsTag < ActiveRecord::Base
end

app/controllers/posts_tags_controller.rb
class PostsTagsController < ApplicationController
  before_action :set_posts_tag, only: [:show, :edit, :update, :destroy]

  # GET /posts_tags
  # GET /posts_tags.json
  def index
    @posts_tags = PostsTag.all
  end

  # GET /posts_tags/1
  # GET /posts_tags/1.json
  def show
  end

  # GET /posts_tags/new
  def new
    @posts_tag = PostsTag.new
  end

  # GET /posts_tags/1/edit
  def edit
  end

  # POST /posts_tags
  # POST /posts_tags.json
  def create
    @posts_tag = PostsTag.new(posts_tag_params)

    respond_to do |format|
      if @posts_tag.save
        format.html { redirect_to @posts_tag, notice: 'Posts tag was successfully created.' }
        format.json { render :show, status: :created, location: @posts_tag }
      else
        format.html { render :new }
        format.json { render json: @posts_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts_tags/1
  # PATCH/PUT /posts_tags/1.json
  def update
    respond_to do |format|
      if @posts_tag.update(posts_tag_params)
        format.html { redirect_to @posts_tag, notice: 'Posts tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @posts_tag }
      else
        format.html { render :edit }
        format.json { render json: @posts_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts_tags/1
  # DELETE /posts_tags/1.json
  def destroy
    @posts_tag.destroy
    respond_to do |format|
      format.html { redirect_to posts_tags_url, notice: 'Posts tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_posts_tag
      @posts_tag = PostsTag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def posts_tag_params
      params.require(:posts_tag).permit(:post_id, :tag_id)
    end
end

app/helpers/posts_tags_helper.rb
module PostsTagsHelper
end

app/views/posts_tags/_form.html.erb
<%= form_for(@posts_tag) do |f| %>
  <% if @posts_tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@posts_tag.errors.count, "error") %> prohibited this posts_tag from being saved:</h2>

      <ul>
      <% @posts_tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :tag_id %><br>
    <%= f.number_field :tag_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts_tags/edit.html.erb
<h1>Editing Posts Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @posts_tag %> |
<%= link_to 'Back', posts_tags_path %>

app/views/posts_tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts Tags</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts_tags.each do |posts_tag| %>
      <tr>
        <td><%= posts_tag.post_id %></td>
        <td><%= posts_tag.tag_id %></td>
        <td><%= link_to 'Show', posts_tag %></td>
        <td><%= link_to 'Edit', edit_posts_tag_path(posts_tag) %></td>
        <td><%= link_to 'Destroy', posts_tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Posts tag', new_posts_tag_path %>

app/views/posts_tags/new.html.erb
<h1>New Posts Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_tags_path %>

app/views/posts_tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @posts_tag.post_id %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @posts_tag.tag_id %>
</p>

<%= link_to 'Edit', edit_posts_tag_path(@posts_tag) %> |
<%= link_to 'Back', posts_tags_path %>